export enum ReceiptErrors {
  RECEIPT_UPLOADED = 'RECEIPT_UPLOADED',
  RECEIPT_HAS_FINGERPRINT_AND_SIGNATURE = 'RECEIPT_HAS_FINGERPRINT_AND_SIGNATURE',
  SIGNATURE_VALID = 'SIGNATURE_VALID',
  UNKNOWN = 'UNKNOWN'
}
