export enum ReceiptErrors {
  RECEIPT_HAS_FINGERPRINT_AND_SIGNATURE = 'RECEIPT_HAS_FINGERPRINT_AND_SIGNATURE',
  SIGNATURE_VALID = 'SIGNATURE_VALID',
  FINGERPRINT_REGISTERED = 'FINGERPRINT_REGISTERED',
  UNKNOWN = 'UNKNOWN'
}
