export enum VerificationSteps {
  INITIALIZE = 'INITIALIZE',
  ENTER_PASSWORD = 'ENTER_PASSWORD',
  RECOVER_BALLOT = 'RECOVER_BALLOT',
  VERIFY_BALLOT_OWNER = 'VERIFY_BALLOT_OWNER',
  VERIFY_BALLOT_CONTENT = 'VERIFY_BALLOT_CONTENT',
  STORE_RECEIPT = 'STORE_RECEIPT'
}
