export enum VerificationErrors {
  LINK_ENTERED = 'LINK_ENTERED',
  PASSWORD_ENTERED = 'PASSWORD_ENTERED',
  LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL',
  DEVICE_PARAMETERS_MATCH = 'DEVICE_PARAMETERS_MATCH',
  SIGNATURE_VALID = 'SIGNATURE_VALID',
  QR_CODE_DECRYPTION = 'QR_CODE_DECRYPTION',
  CHALLENGE_SUCCESSFUL = 'CHALLENGE_SUCCESSFUL',
  ZKP_VALID = 'ZKP_VALID',
  BALLOT_DECODE = 'BALLOT_DECODE',
  UNKNOWN = 'UNKNOWN'
}
